// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2O-BRQIOxYLYHb8h_OLZH2s4LqtKygds',
    appId: '1:281677939055:web:f9834b5f0c016900ada89a',
    messagingSenderId: '281677939055',
    projectId: 'double-v-partners-e36b3',
    authDomain: 'double-v-partners-e36b3.firebaseapp.com',
    storageBucket: 'double-v-partners-e36b3.firebasestorage.app',
    measurementId: 'G-TCFJT46Y5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFQVOvGfUr-n8bCg83cj3GNnVHPhPCCuI',
    appId: '1:281677939055:android:d7f43600309fbf18ada89a',
    messagingSenderId: '281677939055',
    projectId: 'double-v-partners-e36b3',
    storageBucket: 'double-v-partners-e36b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr3GFS-DF1_mWkOXHWBZS5RbDMvNe2phI',
    appId: '1:281677939055:ios:e19fbe5832cc2227ada89a',
    messagingSenderId: '281677939055',
    projectId: 'double-v-partners-e36b3',
    storageBucket: 'double-v-partners-e36b3.firebasestorage.app',
    iosBundleId: 'co.johnathaan.silva.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr3GFS-DF1_mWkOXHWBZS5RbDMvNe2phI',
    appId: '1:281677939055:ios:e19fbe5832cc2227ada89a',
    messagingSenderId: '281677939055',
    projectId: 'double-v-partners-e36b3',
    storageBucket: 'double-v-partners-e36b3.firebasestorage.app',
    iosBundleId: 'co.johnathaan.silva.code',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2O-BRQIOxYLYHb8h_OLZH2s4LqtKygds',
    appId: '1:281677939055:web:7ada7adfe9ed5004ada89a',
    messagingSenderId: '281677939055',
    projectId: 'double-v-partners-e36b3',
    authDomain: 'double-v-partners-e36b3.firebaseapp.com',
    storageBucket: 'double-v-partners-e36b3.firebasestorage.app',
    measurementId: 'G-WJWV65YV6W',
  );
}
